// packages/svelte/src/App.svelte
<script>
  import HelloWorld from './components/HelloWorld.svelte'
</script>

<style>
  .app {
    font-family: Avenir, Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-align: center;
    color: #2c3e50;
    margin-top: 60px;
  }
</style>

<main class="app">
  <HelloWorld name="World" />
</main>

// packages/vue/src/App.vue
<template>
  <HelloWorldFn name="World"/>
</template>

<script>
import HelloWorldFn from './components/HelloWorldFn.vue'
// import HelloWorldTpl from './components/HelloWorldTpl.vue'

export default {
  name: 'App',
  components: {
    HelloWorldFn,
    // HelloWorldTpl
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
